spring.application.name=guardhouse

app.seed.admin.password=${ADMIN_PASSWORD}
app.seed.admin.email=${ADMIN_EMAIL}


#auth
jwt.secret=${JWT_SECRET}
jwt.expiration-ms=${JWT_EXP}

#mongodb
spring.data.mongodb.uri=mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@localhost:${MONGO_PORT}/${MONGO_DB}?authSource=admin